spring:
  config:
    activate:
      on-profile: apod
webscraper:
  crawler:
    image:
      number-images: 100
    web:
      start-download-automatically: true
      start-analysis-automatically: true
      start-url: https://apod.nasa.gov/apod/astropix.html
      number-pages: 200
      consent-cookies: false
    sites:
      white-list:
        - https://apod.nasa.gov
      black-list:
