spring:
  config:
    activate:
      on-profile: heise
  web:
    resources:
      static-locations: file:C:\Users\jurge\AppData\Local\Temp\webscraper
webscraper:
  crawler:
    image:
      start-download-automatically: false
      directory: C:\Users\jurge\AppData\Local\Temp\webscraper
      number-images: 1000
      file-extensions:
        - jpeg
        - jpg
        - png
        - webp
    web:
      start-url: https://www.heise.de
      start-download-automatically: false
      number-pages: 100
      start-analysis-automatically: false
      consent-cookies: true
      consent-css-selector:
        - button[title='Zustimmen']
        #- button[title='Agree']
      javascript:
        - document.querySelectorAll('a-sticky-footer button[data-hide-trigger]').forEach((element) => element.click())
    sites:
      whitelist:
        - https://heise.cloudimg.io
        - https://www.heise.de
      blacklist:
        - https://aktionen.heise.de/
        - https://blog.heise-academy.de/
        - https://business-services.heise.de/
        - https://compaliate.heise.de/
        - https://facebook.com/heiseonline
        - https://ftp.heise.de/
        - https://getpocket.com/
        - https://heise-academy.de/
        - https://it-kenner.heise.de/
        - https://itunes.apple.com/
        - https://jobs.heise.de/
        - https://kiupdate.podigee.io/episodes
        - https://kurzinformiert.podigee.io/episodes
        - https://m.me/heiseonline
        - https://maker-faire.de/
        - https://mediadaten.heise.de/
        - https://play.google.com/
        - https://premium.usenext.com/
        - https://pubads.g.doubleclick.net/
        - https://security-tour.heise.de/
        - https://shop.heise.de/
        - https://spiele.heise.de/
        - https://survey.vocatus.de/
        - https://t3n.de/
        - https://telepolis.de/
        - https://twitter.com/
        - https://u.openx.net/
        - https://webinare.heise.de/
        - https://www.amazon.de/
        - https://www.ct.de/
        - https://www.eweka.nl/
        - https://www.facebook.com/
        - https://www.geizhals.at/
        - https://www.heise-events.de/
        - https://www.heise-gruppe.de/
        - https://www.heise-medien.de/
        - https://www.heise-regioconcept.de/
        - https://www.heise.de/account/cancellation
        - https://www.heise.de/api/
        - https://www.heise.de/benachrichtigungen
        - https://www.heise.de/ct/feed.xml
        - https://www.heise.de/developer/rss/news-atom.xml
        - https://www.heise.de/download
        - https://www.heise.de/forum
        - https://www.heise.de/foto
        - https://www.heise.de/foto/news/foren/
        - https://www.heise.de/foto/produktdaten/foren/
        - https://www.heise.de/kontakt/
        - https://www.heise.de/loseblattwerke/
        - https://www.heise.de/mac-and-i/kontakt
        - https://www.heise.de/mac-and-i/news-atom.xml
        - https://www.heise.de/make/kontakt
        - https://www.heise.de/make/rss/hardware-hacks-atom.xml
        - https://www.heise.de/news-atom.xml
        - https://www.heise.de/news-extern/news.html
        - https://www.heise.de/newsletter/
        - https://www.heise.de/plus/
        - https://www.heise.de/preisvergleich/
        - https://www.heise.de/rss.xml
        - https://www.heise.de/select/
        - https://www.heise.de/sso/
        - https://www.heise.de/tarifrechner
        - https://www.heise.de/thema/Datenleck.xml
        - https://www.heise.de/thema/Digital-Health.xml
        - https://www.heise.de/thema/Energie.xml
        - https://www.heise.de/thema/Fritzbox.xml
        - https://www.heise.de/thema/Karriere.xml
        - https://www.heise.de/thema/Kuenstliche-Intelligenz.xml
        - https://www.heise.de/thema/Quiz.xml
        - https://www.heise.de/thema/Raumfahrt.xml
        - https://www.heise.de/thema/Smart-Home.xml
        - https://www.heise.de/thema/Windows.xml
        - https://www.heise.de/themen/
        - https://www.heise.de/tools/
        - https://www.heise.de/tp/
        - https://www.heisegroup.de/
        - https://www.hostg.xyz/
        - https://www.instagram.com/
        - https://www.interred.de/
        - https://www.ix-konferenz.de
        - https://www.plusline.net/
        - https://www.techstage.de/
        - https://www.telepolis.de/
        - https://www.twitter.com/
        - https://www.xing.com/
        - https://www.youtube.com/
  picturechoice:
    directory: C:\Users\jurge\AppData\Local\Temp\webscraper
